### ISSUE TITLE
Make dataset available on HF

### ISSUE THREAD

**Issue by NielsRogge** [zhliu0106/learning-to-refuse#1]
Hi there,

Congrats on releasing this dataset! Niels here from the open-source team at Hugging Face. I discovered your work through the paper page: https://huggingface.co/papers/2407.10058 (feel free to claim it).

I was wondering whether you would be up for making your dataset available on the hub, such that people can do:

```python
from datasets import load_dataset

dataset = load_dataset("your-hf-username/return")
```

? This would also ensure a dataset viewer, which allows people to easily discover and read the first few rows of the dataset in the browser, along with tags like "safety".

See here for a guide: https://huggingface.co/docs/datasets/loading.

It could then also be linked to the paper page, as explained here: https://huggingface.co/docs/hub/en/datasets-cards#linking-a-paper

**Comment by zhliu0106** [comment]
Thx for your suggestion!

On it now!

**Comment by NielsRogge** [comment]
Great, thank you! Would be great to mention it in the README of this repo :)

**Comment by zhliu0106** [comment]
Done! :)
