### ISSUE TITLE
About the pred_answer

### ISSUE THREAD

**Issue by LetheSec** [zhliu0106/learning-to-refuse#3]
Hi, 

In the data you provided, the `pred_answer` of Llama-3-8B-Instruct are concise and clear. However, in my experiments, the model generally produced longer responses.

Did you use any additional prompts or some other processing? 

Looking forward to your reply. Thanks.

**Comment by zhliu0106** [comment]
It may be the generation_config/config/tokenizer_config problem. Please use the latest llama3-8b config files

**Comment by zhliu0106** [comment]
I used this prompt:

TEMPLATE = "Answer the given question in no more than one sentence.\nPlease keep your answer short and concise.\nQuestion: __question__\nAnswer:"

Replace __question__ with the specific question.

I will release all code after finishing the recent deadline!

**Comment by LetheSec** [comment]
> I used this prompt:
> 
> TEMPLATE = "Answer the given question in no more than one sentence.\nPlease keep your answer short and concise.\nQuestion: **question**\nAnswer:"TEMPLATE = "用不超过一句话回答给定的问题。\n请保持你的答案简短明了。\n问题：**问题**\n答案："
> 
> Replace **question** with the specific question.
> 
> I will release all code after finishing the recent deadline!

This makes sense. Thank you for your reply.
